### ISSUE TITLE
Deduce server settings from package.json if it has a vscode extension

### ISSUE THREAD

**Issue by rwols** [sublimelsp/lsp_utils#10]
For instance look at this one:

https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json

We can parse the `contributes` dict and translate it to `settings`.

**Comment by rchl** [comment]
It's a configuration for the client (extension) though. It doesn't necessarily map 1:1 to server options.

But in any case, if we would to do that, are you thinking about generating our settings from those at commit time or runtime?

**Comment by rchl** [comment]
On the other hand, even if we would send more options then needed (since contributed settings can be a superset of server options) it wouldn't hurt.

VSCode sends **all** configuration settings in `initialize` request, including those that extensions contribute.
`workspace/didChangeConfiguration` seems to be more filtered/specific but I'm not sure what's the logic there.

But yeah, the question still stands how would we turn those into our settings. I guess at build/commit time?

**Comment by rwols** [comment]
> But yeah, the question still stands how would we turn those into our settings? I guess at build/commit time?

We implemented this with a command in the command palette that you run when you maintain/write/create/update the LSP-* package.
