### ISSUE TITLE
Prefer using IPv4 for downloading packages from NPM

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/lsp_utils#98]
# Issue

A LSP-copilot user uses his local Node.js v19 setup and it gives error as in https://github.com/TerminalFi/LSP-copilot/issues/92#issuecomment-1464821634.

> npm ERR! FetchError: request to [registry.npmjs.org/copilot-node-server/-/copilot-node-server-1.8.3.tgz](https://registry.npmjs.org/copilot-node-server/-/copilot-node-server-1.8.3.tgz) failed, reason: connect ECONNREFUSED 2606:4700::6810:1923:443

After some investigation, as of Node.js v17, its DNS resolution prefers `verbatim`, which may gives IPv6 result. But however, the user actually have IPv6 disabled in his VPN setup (is this a convention?).

- https://github.com/nodejs/node/pull/39987
- https://github.com/nodejs/node/issues/40537
- https://github.com/npm/cli/issues/4163

# Proposal

Add `--dns-result-order=ipv4first` CLI option when starting Node/Electron.

Note that this option first appears in Node.js v16. For Node.js <= v15, it results in `bad option: --dns-result-order=ipv4first`.

Or can the user add `--dns-result-order=ipv4first` by himself?

**Comment by rchl** [comment]
I wouldn't want to add this option unconditionally in all cases just because there is someone out there with such issue.

Also, based on your investigation, for "built-in" node/electron we shouldn't need it anyway because IPv6 is not the default in v16.

Maybe there could exist an option to pass extra arguments to node runtime. But it wouldn't make it easier to users to figure out how to fix this issue on their own.

**Comment by jfcherng** [comment]
I think we can close this until v18 is shipped widely someday and if it's really an issue.
